name: Deploy D-VirtOS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🏗️ Setup & Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          cp -r dist/* ../ 

      - name: 📦 Setup & Install Backend
        run: |
          cd backend
          composer install --no-dev --optimize-autoloader

      - name: 🚀 Deploy via Rsync (SSH)
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: ${{ secrets.SSH_REMOTE_PATH }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: >
            --exclude='.git*'
            --exclude='.github*'
            --exclude='.ssh/'
            --exclude='cgi-bin/'
            --exclude='**/node_modules/**'
            --exclude='frontend/src/**'
            --exclude='frontend/public/**'
            --exclude='backend/tests/**'
            --exclude='**/.env'
            --exclude='docker-compose.yml'
            --exclude='Dockerfile'
            --exclude='README.md'
            --exclude='LEIAME.md'
            --exclude='LICENSE'
            --exclude='Makefile'
            --exclude='makefile'